kind: Deployment
apiVersion: apps/v1
metadata:
  name: [group_name]
  namespace: group[group_number]
  labels:
    app: [group_name]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: [group_name]
  template:
    metadata:
      labels:
        app: [group_name]
    spec:
      containers:
      - name: [group_name]
        image: [your_image_name:latest]
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: [group_name]
  namespace: group03
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: [group_name]
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: [group_name]route
  namespace: group03
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`[group_number].web.dops.tech`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: [group_name]
      port: 80
  tls:
    certResolver: myresolver
